---
name: Build
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Login
      uses: docker/login-action@v1
      if: secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_PASSWORD != ''
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push to Docker Hub
      id: hub_build
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: compilerexplorer/gcc-cross-builder:latest
        cache-from: type=registry,ref=compilerexplorer/gcc-cross-builder:latest
        cache-to: type=inline
    - name: Docker Hub Image Digest
      run: echo ${{ steps.hub_build.outputs.digest }}
